// AUTO-GENERATED by scripts/generate-spritesheets.mjs — do not edit.
// Resolves packed Phaser spritesheets to URIs for the Expo wrapper.
import { Image } from 'react-native';

const RAW = {
  'knight_idle': require('../../assets/phaser/knight_idle.png'),
  'knight_walk': require('../../assets/phaser/knight_walk.png'),
  'knight_run': require('../../assets/phaser/knight_run.png'),
  'knight_jump': require('../../assets/phaser/knight_jump.png'),
  'knight_attack': require('../../assets/phaser/knight_attack.png'),
  'mage_idle': require('../../assets/phaser/mage_idle.png'),
  'mage_walk': require('../../assets/phaser/mage_walk.png'),
  'mage_run': require('../../assets/phaser/mage_run.png'),
  'mage_jump': require('../../assets/phaser/mage_jump.png'),
  'mage_attack': require('../../assets/phaser/mage_attack.png'),
  'rogue_idle': require('../../assets/phaser/rogue_idle.png'),
  'rogue_walk': require('../../assets/phaser/rogue_walk.png'),
  'rogue_run': require('../../assets/phaser/rogue_run.png'),
  'rogue_jump': require('../../assets/phaser/rogue_jump.png'),
  'rogue_attack': require('../../assets/phaser/rogue_attack.png'),
  'pinkMonster_idle': require('../../assets/phaser/pinkMonster_idle.png'),
  'pinkMonster_walk': require('../../assets/phaser/pinkMonster_walk.png'),
  'pinkMonster_run': require('../../assets/phaser/pinkMonster_run.png'),
  'pinkMonster_jump': require('../../assets/phaser/pinkMonster_jump.png'),
  'pinkMonster_attack': require('../../assets/phaser/pinkMonster_attack.png'),
  'owletMonster_idle': require('../../assets/phaser/owletMonster_idle.png'),
  'owletMonster_walk': require('../../assets/phaser/owletMonster_walk.png'),
  'owletMonster_run': require('../../assets/phaser/owletMonster_run.png'),
  'owletMonster_jump': require('../../assets/phaser/owletMonster_jump.png'),
  'owletMonster_attack': require('../../assets/phaser/owletMonster_attack.png'),
  'dudeMonster_idle': require('../../assets/phaser/dudeMonster_idle.png'),
  'dudeMonster_walk': require('../../assets/phaser/dudeMonster_walk.png'),
  'dudeMonster_run': require('../../assets/phaser/dudeMonster_run.png'),
  'dudeMonster_jump': require('../../assets/phaser/dudeMonster_jump.png'),
  'dudeMonster_attack': require('../../assets/phaser/dudeMonster_attack.png'),
  'plant1_idle': require('../../assets/phaser/plant1_idle.png'),
  'plant1_walk': require('../../assets/phaser/plant1_walk.png'),
  'plant1_attack': require('../../assets/phaser/plant1_attack.png'),
  'plant1_death': require('../../assets/phaser/plant1_death.png'),
  'plant2_idle': require('../../assets/phaser/plant2_idle.png'),
  'plant2_walk': require('../../assets/phaser/plant2_walk.png'),
  'plant2_attack': require('../../assets/phaser/plant2_attack.png'),
  'plant2_death': require('../../assets/phaser/plant2_death.png'),
  'background': require('../../assets/phaser/background.png'),
  'ability': require('../../assets/phaser/ability.png'),
  'settings': require('../../assets/phaser/settings.png'),
  'heart_1': require('../../assets/phaser/heart_1.png'),
  'heart_2': require('../../assets/phaser/heart_2.png'),
  'heart_3': require('../../assets/phaser/heart_3.png'),
  'heart_4': require('../../assets/phaser/heart_4.png'),
  'heart_5': require('../../assets/phaser/heart_5.png'),
  'btn_left': require('../../assets/phaser/btn_left.png'),
  'btn_right': require('../../assets/phaser/btn_right.png'),
  'btn_up': require('../../assets/phaser/btn_up.png'),
  'btn_down': require('../../assets/phaser/btn_down.png'),
};

const resolve = (m) => Image.resolveAssetSource(m).uri;

export const MANIFEST = {
  "characters": {
    "knight": {
      "idle": {
        "key": "knight_idle",
        "frameWidth": 67,
        "frameHeight": 81,
        "frameCount": 12
      },
      "walk": {
        "key": "knight_walk",
        "frameWidth": 55,
        "frameHeight": 61,
        "frameCount": 6
      },
      "run": {
        "key": "knight_run",
        "frameWidth": 60,
        "frameHeight": 62,
        "frameCount": 8
      },
      "jump": {
        "key": "knight_jump",
        "frameWidth": 81,
        "frameHeight": 67,
        "frameCount": 7
      },
      "attack": {
        "key": "knight_attack",
        "frameWidth": 90,
        "frameHeight": 78,
        "frameCount": 5
      }
    },
    "mage": {
      "idle": {
        "key": "mage_idle",
        "frameWidth": 62,
        "frameHeight": 60,
        "frameCount": 14
      },
      "walk": {
        "key": "mage_walk",
        "frameWidth": 51,
        "frameHeight": 62,
        "frameCount": 6
      },
      "run": {
        "key": "mage_run",
        "frameWidth": 57,
        "frameHeight": 63,
        "frameCount": 8
      },
      "jump": {
        "key": "mage_jump",
        "frameWidth": 68,
        "frameHeight": 69,
        "frameCount": 7
      },
      "attack": {
        "key": "mage_attack",
        "frameWidth": 82,
        "frameHeight": 79,
        "frameCount": 7
      }
    },
    "rogue": {
      "idle": {
        "key": "rogue_idle",
        "frameWidth": 50,
        "frameHeight": 54,
        "frameCount": 17
      },
      "walk": {
        "key": "rogue_walk",
        "frameWidth": 46,
        "frameHeight": 54,
        "frameCount": 6
      },
      "run": {
        "key": "rogue_run",
        "frameWidth": 57,
        "frameHeight": 56,
        "frameCount": 8
      },
      "jump": {
        "key": "rogue_jump",
        "frameWidth": 58,
        "frameHeight": 62,
        "frameCount": 7
      },
      "attack": {
        "key": "rogue_attack",
        "frameWidth": 63,
        "frameHeight": 55,
        "frameCount": 7
      }
    },
    "pinkMonster": {
      "idle": {
        "key": "pinkMonster_idle",
        "frameWidth": 140,
        "frameHeight": 204,
        "frameCount": 4
      },
      "walk": {
        "key": "pinkMonster_walk",
        "frameWidth": 129,
        "frameHeight": 203,
        "frameCount": 6
      },
      "run": {
        "key": "pinkMonster_run",
        "frameWidth": 142,
        "frameHeight": 203,
        "frameCount": 6
      },
      "jump": {
        "key": "pinkMonster_jump",
        "frameWidth": 127,
        "frameHeight": 173,
        "frameCount": 8
      },
      "attack": {
        "key": "pinkMonster_attack",
        "frameWidth": 162,
        "frameHeight": 182,
        "frameCount": 4
      }
    },
    "owletMonster": {
      "idle": {
        "key": "owletMonster_idle",
        "frameWidth": 173,
        "frameHeight": 202,
        "frameCount": 4
      },
      "walk": {
        "key": "owletMonster_walk",
        "frameWidth": 158,
        "frameHeight": 202,
        "frameCount": 6
      },
      "run": {
        "key": "owletMonster_run",
        "frameWidth": 172,
        "frameHeight": 200,
        "frameCount": 6
      },
      "jump": {
        "key": "owletMonster_jump",
        "frameWidth": 185,
        "frameHeight": 242,
        "frameCount": 8
      },
      "attack": {
        "key": "owletMonster_attack",
        "frameWidth": 202,
        "frameHeight": 217,
        "frameCount": 4
      }
    },
    "dudeMonster": {
      "idle": {
        "key": "dudeMonster_idle",
        "frameWidth": 135,
        "frameHeight": 203,
        "frameCount": 4
      },
      "walk": {
        "key": "dudeMonster_walk",
        "frameWidth": 137,
        "frameHeight": 203,
        "frameCount": 6
      },
      "run": {
        "key": "dudeMonster_run",
        "frameWidth": 156,
        "frameHeight": 204,
        "frameCount": 6
      },
      "jump": {
        "key": "dudeMonster_jump",
        "frameWidth": 167,
        "frameHeight": 205,
        "frameCount": 8
      },
      "attack": {
        "key": "dudeMonster_attack",
        "frameWidth": 198,
        "frameHeight": 210,
        "frameCount": 4
      }
    }
  },
  "mobs": {
    "plant1": {
      "idle": {
        "key": "plant1_idle",
        "frameWidth": 63,
        "frameHeight": 48,
        "frameCount": 4
      },
      "walk": {
        "key": "plant1_walk",
        "frameWidth": 68,
        "frameHeight": 46,
        "frameCount": 6
      },
      "attack": {
        "key": "plant1_attack",
        "frameWidth": 87,
        "frameHeight": 48,
        "frameCount": 6
      },
      "death": {
        "key": "plant1_death",
        "frameWidth": 71,
        "frameHeight": 45,
        "frameCount": 6
      }
    },
    "plant2": {
      "idle": {
        "key": "plant2_idle",
        "frameWidth": 40,
        "frameHeight": 41,
        "frameCount": 4
      },
      "walk": {
        "key": "plant2_walk",
        "frameWidth": 44,
        "frameHeight": 41,
        "frameCount": 6
      },
      "attack": {
        "key": "plant2_attack",
        "frameWidth": 53,
        "frameHeight": 45,
        "frameCount": 7
      },
      "death": {
        "key": "plant2_death",
        "frameWidth": 48,
        "frameHeight": 41,
        "frameCount": 10
      }
    }
  },
  "level": {
    "background": "background",
    "ability": "ability",
    "settings": "settings",
    "heart_1": "heart_1",
    "heart_2": "heart_2",
    "heart_3": "heart_3",
    "heart_4": "heart_4",
    "heart_5": "heart_5"
  },
  "buttons": {
    "left": "btn_left",
    "right": "btn_right",
    "up": "btn_up",
    "down": "btn_down"
  }
};

// { key: uri } for every packed spritesheet / image.
export function resolvePhaserTextures() {
  const out = {};
  for (const k of Object.keys(RAW)) out[k] = resolve(RAW[k]);
  return out;
}
