const base = {
  fonts: {
    headingBold: 'REM-Bold',
    heading: 'REM-Regular',
    bodyBold: 'Sen-Bold',
    body: 'Sen-Regular',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 16,
    lg: 24,
    full: 999,
  },
};

export const light = {
  ...base,
  mode: 'light',
  colors: {
    background: '#F2F2F0',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    primary: '#7C7BF0',
    secondary: '#F5A623',
    success: '#4CAF50',
    error: '#FF5252',
    textPrimary: '#1A1A1A',
    textSecondary: '#6B7280',
    border: '#E5E7EB',
    chalk: '#FFFFFF',
    gradientVectorStart: '#7C7BF0',
    gradientVectorEnd: '#5A4FE0',
    gradientDiffStart: '#F5A623',
    gradientDiffEnd: '#E8951A',
    expBlue: '#5B8DEF',
    streakOrange: '#F5A623',
    completedRed: '#FF6B6B',
    sidebarHeaderStart: '#7C7BF0',
    sidebarHeaderEnd: '#5A4FE0',
    statusBar: 'dark',
    inputBg: '#FAFAFA',
  },
};

export const dark = {
  ...base,
  mode: 'dark',
  colors: {
    background: '#1A1A2E',
    surface: '#2D2D44',
    card: '#2D2D44',
    primary: '#8B8AF5',
    secondary: '#F5A623',
    success: '#66BB6A',
    error: '#FF6B6B',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0B8',
    border: '#3D3D5C',
    chalk: '#1A1A2E',
    gradientVectorStart: '#7C7BF0',
    gradientVectorEnd: '#5A4FE0',
    gradientDiffStart: '#F5A623',
    gradientDiffEnd: '#E8951A',
    expBlue: '#6BA5F7',
    streakOrange: '#F5A623',
    completedRed: '#FF6B6B',
    sidebarHeaderStart: '#7C7BF0',
    sidebarHeaderEnd: '#5A4FE0',
    statusBar: 'light',
    inputBg: '#3D3D5C',
  },
};

export const pink = {
  ...base,
  mode: 'pink',
  colors: {
    background: '#FFF0F5',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    primary: '#E8879B',
    secondary: '#F5A623',
    success: '#4CAF50',
    error: '#FF5252',
    textPrimary: '#2D1B2E',
    textSecondary: '#8B6B7E',
    border: '#F0D5E0',
    chalk: '#FFFFFF',
    gradientVectorStart: '#E8879B',
    gradientVectorEnd: '#D4607A',
    gradientDiffStart: '#F5A623',
    gradientDiffEnd: '#E8951A',
    expBlue: '#5B8DEF',
    streakOrange: '#F5A623',
    completedRed: '#FF6B6B',
    sidebarHeaderStart: '#E8879B',
    sidebarHeaderEnd: '#D4607A',
    statusBar: 'dark',
    inputBg: '#FFF5F8',
  },
};

const theme = light;
export default theme;
